wallpaper {
    monitor = DP-2
    path = ~/.config/sysconfig/hyprpaper/wallpaper/wide_tokyonight_lines.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/.config/sysconfig/hyprpaper/wallpaper/wide_tokyonight_lines.png
    fit_mode = cover
}
