bind = $mainMod, Return, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, F, exec, vivaldi
bind = $mainMod, D, exec, discord
bind = $mainMod, X, exec, steam
bind = $mainMod, T, exec, code

# Window movement
bind = SUPER SHIFT, H, movewindow, mon:DP-2
bind = SUPER SHIFT, L, movewindow, mon:DP-3
bind = $mainMod CTRL, left, swapwindow, l
bind = $mainMod CTRL, right, swapwindow, r
bind = $mainMod CTRL, up, swapwindow, u
bind = $mainMod CTRL, down, swapwindow, d